version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing kubectl..."
      - KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt)
      - curl -sL --retry 5 --retry-all-errors --retry-delay 3 -o kubectl "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster

  build:
    commands:
      - echo "Deploying application to EKS..."
      - kubectl set image deployment/brain-tasks-app brain-tasks-app=954568385582.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - kubectl rollout status deployment/brain-tasks-app --timeout=300s

  post_build:
    commands:
      - echo "Deployment completed successfully"
      - kubectl get deployment brain-tasks-app
      - kubectl get pods
      - kubectl get service brain-tasks-app
